### ISSUE TITLE
do sorting/dedup in sql

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/contributors#4]
This is me being a noob at diesel

https://github.com/steveklabnik/contributors/blob/master/src/main.rs#L97-L98

https://github.com/steveklabnik/contributors/blob/master/src/main.rs#L123-L124

**Comment by bwo** [comment]
fyi the second link there now points to returning a 404. I assume you mean: https://github.com/steveklabnik/contributors/blob/f041f00117699bc90c5b062536a65fdcc26cce94/src/main.rs#L131-L136 ?

**Comment by ThatOtherPerson** [comment]
This has probably been resolved by #23, #24, and #27.

**Comment by steveklabnik** [comment]
Yes, thank you!
